<a href="https://colab.research.google.com/github/vachkim/LECTURE/blob/master/PYTHON/Lec_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## - 넘파이
- 넘파이는 숫자를 다루는 패키지이다
- import numpy를 한 뒤에 사용하자

In [ ]:
import numpy as np

### 1) 넘파이 배열
- 넘파이는 주로 배열을 다루는 기능을 수행한다
- np.array를 활용하면 배열을 만들 수 있다

In [ ]:
arr= np.array([1,2,3,4])
print(arr)

[1 2 3 4]


- 이 외 특정값이 들어간 배열을 만들 수도 있다
- np.특정값(배열)의 순으로 입력한다

In [ ]:
np.zeros((3,3)) #배열은 (행의 수, 열의 수)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

- np.arrange는 array와 달리 주어진 수만큼의 수를 리스트처럼 출력한다
- arange(a,b,c)로도 사용이 가능하다_이 경우에는 a부터 b까지 c씩 커지는 배열이 나온다
- 이를 행열로 다듬는 reshpae()와 함께 사용하면 또다른 array를 만들 수 있다

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [ ]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(24).reshape(2,3,2,2) 
#이렇게 4개의 수가 들어갈 경우
#뒤의 2개의 수가 행열에 대한 것
#앞의 2개는 행렬의 배열에 대한 것이다

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

- 넘파이의 특징 중 하나는 다차원의 배열을 만들 수 있다는 것



In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

- 형성된 array끼리의 연산도 가능
- 이때에는 같은 차원의 데이터끼리 연산된다

In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

print(arr1+arr2)          #배열끼리의 합 두가지 방법 
print('-'*20)
print(np.add(arr1,arr2))
print('-'*20)
print(arr1*arr2)          #배열끼리의 곱 두가지 방법
print('-'*20)
print(np.multiply(arr1,arr2))

[[ 6  8]
 [10 12]]
--------------------
[[ 6  8]
 [10 12]]
--------------------
[[ 5 12]
 [21 32]]
--------------------
[[ 5 12]
 [21 32]]


- 데이터 프레임과 마찬가지로 배열을 슬라이싱하는 것도 중요하다
- [시작행:끝행,시작열:끝열]의 순서로 표시해주면 데이터가 들어감

In [ ]:
arr=np.array([[1,2,3]
             ,[4,5,6]
             ,[7,8,9]])
print(arr[0,2])
print(arr[0:2,1:3])

3
[[2 3]
 [5 6]]
