<a href="https://colab.research.google.com/github/vachkim/LECTURE/blob/master/MINING/Lec_KOREAN_MINING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. 프로그램 설치
- 한글 분석은 영어와 달리 기본 패키지를 활용할 수 없다 
- 따라서 형태소 분석을 위한 프로그램을 별도로 설치해주는 것이 필요하다

### 1) MeCAB설치 _ Win용
- C드라이브에 mecab폴더를 만든다
- [다음](https://github.com/Pusnow/mecab-ko-msvc/releases/tag/release-0.9.2-msvc-3)에서 win버전에 맞는 파일을 다운받는다
- 만들어놓은 mecab폴더에 다운 받은 파일들을 넣어준다
- [다음](https://github.com/Pusnow/mecab-ko-dic-msvc/releases/tag/mecab-ko-dic-2.1.1-20180720-msvc)에서 첫번째 압축 파일을 다운받는다
- [다음](https://github.com/Pusnow/mecab-python-msvc/releases/tag/mecab_python-0.996_ko_0.9.2_msvc-2)에서 파이썬 버전에 맞는 파일을 다운받은 뒤, 현재 주피터 노트북이 실행되고 있는 폴더에 넣어준다
- 주피터 노트북이 실행되는 폴더에 파이썬 파일을 만들어 !pip install을 실행한다

### 2) KoNLPy 설치 _ Win용
- [다음](https://www.oracle.com/java/technologies/javase-downloads.html)에서 버전에 맞는 EXE파일을 다운로드 받는다
- 다운받은 JAVA EXE파일을 실행해 설치한다
- 내 컴퓨터 > 속성 > 고급 시스템 설정 > 환경변수 > 시스템 변수 > Path에서 다운받은 java의 폴더 경로를 추가한다
- Visual Studio를 설치한다
- [다음](https://www.lfd.uci.edu/~gohlke/pythonlibs/#jpype)에서 파이썬 버전에 맞는 JPype1을 다운받는다
- 주피터 노트북에 파이썬 파일을 하나 만들어 !pip install을 실행, Jpype1을 설치한다
- 이후 !pip install konlpy를 진행한다

## 2. 텍스트 전처리
- 텍스트를 자연어 처리를 위해 용도에 맞도록 표준화하는 작업

### 1) 토큰화
- 텍스트를 자연어 처리를 위해 분리 하는 것

In [ ]:
text = '인생은 모두가 함께하는 여행이다. 매일매일 사는 동안 우리가 할 수 있는 건 최선을 다해 이 멋진 여행을 만끽하는 것이다'
print(text.split()) #공백으로 토큰화_그러나 한글은 조사, 어미 등이 붙어있기 때문에 공백으로 토큰화는 좋지 않다

['인생은', '모두가', '함께하는', '여행이다.', '매일매일', '사는', '동안', '우리가', '할', '수', '있는', '건', '최선을', '다해', '이', '멋진', '여행을', '만끽하는', '것이다']


- 토큰화에 필요한 라이브러리를 다운받는다

In [ ]:
!pip install konlpy #konlpy는 형태소 분석에 필요한 여러 패키지를 포함한 라이브러리다
from konlpy.tag import Komoran
from konlpy.tag import Hannanum
from konlpy.tag import Okt
from konlpy.tag import Kkma

     |████████████████████████████████| 19.4MB 1.5MB/s 
     |████████████████████████████████| 3.8MB 40.1MB/s 
     |████████████████████████████████| 92kB 8.7MB/s 
  Found existing installation: tweepy 3.6.0
    Uninstalling tweepy-3.6.0:
      Successfully uninstalled tweepy-3.6.0
  Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3


- 각 패키지에 들어가는 입력값이 Str타입임을 유의하자

In [ ]:
komoran = Komoran() #호출한 패키지는 사용을 위해 선언이 필수적으로 해주어야 한다
komoran_tokens = komoran.morphs(text) #komoran의 morphs를 사용해 토큰화
print(komoran_tokens)

['인생', '은', '모두', '가', '함께', '하', '는', '여행', '이', '다', '.', '매일', '매일', '살', '는', '동안', '우리', '가', '하', 'ㄹ', '수', '있', '는', '건', '최선', '을', '다', '하', '아', '이', '멋지', 'ㄴ', '여행', '을', '만끽', '하', '는', '것', '이', '다']


- 사용할 수 있는 옵션으로 morphs와 더불어 noun, pos 등이 있다
  + noun은 명사만 추출
  + pos는 품사 단위로 추출

In [ ]:
komoran = Komoran() #호출한 패키지는 사용을 위해 선언이 필수적으로 해주어야 한다
komoran_tokens = komoran.pos(text) #komoran의 morphs를 사용해 토큰화
print(komoran_tokens)

[('인생', 'NNG'), ('은', 'JX'), ('모두', 'NNG'), ('가', 'JKS'), ('함께', 'MAG'), ('하', 'XSV'), ('는', 'ETM'), ('여행', 'NNG'), ('이', 'VCP'), ('다', 'EF'), ('.', 'SF'), ('매일', 'MAG'), ('매일', 'MAG'), ('살', 'VV'), ('는', 'ETM'), ('동안', 'NNG'), ('우리', 'NP'), ('가', 'JKS'), ('하', 'VV'), ('ㄹ', 'ETM'), ('수', 'NNB'), ('있', 'VV'), ('는', 'ETM'), ('건', 'NNB'), ('최선', 'NNG'), ('을', 'JKO'), ('다', 'MAG'), ('하', 'XSV'), ('아', 'EC'), ('이', 'MM'), ('멋지', 'VA'), ('ㄴ', 'ETM'), ('여행', 'NNG'), ('을', 'JKO'), ('만끽', 'NNG'), ('하', 'XSV'), ('는', 'ETM'), ('것', 'NNB'), ('이', 'VCP'), ('다', 'EC')]


- 위처럼 pos를 사용하면 품사 정보도 한번에 추출 가능하다

In [ ]:
hannanum = Hannanum()
hannanum_tokens = hannanum.morphs(text)
print(hannanum_tokens)

['인생', '은', '모두', '가', '함께하', '는', '여행', '이', '다', '.', '매일매일', '사', '는', '동안', '우리', '가', '하', 'ㄹ', '수', '있', '는', '거', '은', '최선', '을', '다하', '어', '이', '멋지', 'ㄴ', '여행', '을', '만끽', '하', '는', '것', '이', '다']


- 위처럼 Komoran과 Hannanum은 세밀하게 토큰화를 진행한다
- 즉 어간/어미 단위까지 구분해 토큰화가 이루어진다

In [ ]:
okt = Okt()
okt_tokens = okt.morphs(text)
print(okt_tokens)

['인생', '은', '모두', '가', '함께', '하는', '여행', '이다', '.', '매', '일', '매일', '사는', '동안', '우리', '가', '할', '수', '있는', '건', '최선', '을', '다해', '이', '멋진', '여행', '을', '만끽', '하는', '것', '이다']


- Okt는 품사단위로 토큰화 하기 때문에 상대적으로 토큰화 단위가 크다
- Okt는 SNS등에서 사용되는 이모티콘 등을 구분할 수 있다는 장점이 있다 

In [ ]:
kkma=Kkma()
kkma_tokens = kkma.morphs(text)
print(kkma_tokens)

['인생', '은', '모두', '가', '함께', '하', '는', '여행', '이', '다', '.', '매일', '매일', '살', '는', '동안', '우리', '가', '하', 'ㄹ', '수', '있', '는', '것', '은', '최선', '을', '다하', '어', '이', '멋지', 'ㄴ', '여행', '을', '만끽', '하', '는', '것', '이', '다']


### 2) 품사부착
- 각 토큰에 품사정보를 추가하여 분석시 불필요한 품사를 제거하거나 필요한 품사만 필터링한다

In [ ]:
komoranTag = []
for token in komoran_tokens: #토큰화된 결과물은 리스트 형태이기 때문에 for문을 사용해 하나씩 꺼내는 과정이 필요
  komoranTag += komoran.pos(token)
print(komoranTag)

[('인생', 'NNG'), ('은', 'NNP'), ('모두', 'MAG'), ('가', 'VV'), ('아', 'EC'), ('함께', 'MAG'), ('하', 'NNG'), ('늘', 'VV'), ('ㄴ', 'ETM'), ('여행', 'NNG'), ('이', 'MM'), ('다', 'MAG'), ('.', 'SF'), ('매일', 'MAG'), ('매일', 'MAG'), ('살', 'VV'), ('ㄹ', 'ETM'), ('늘', 'VV'), ('ㄴ', 'ETM'), ('동안', 'NNG'), ('우리', 'NP'), ('가', 'VV'), ('아', 'EC'), ('하', 'NNG'), ('ㄹ', 'NA'), ('수', 'NNB'), ('있', 'VV'), ('늘', 'VV'), ('ㄴ', 'ETM'), ('건', 'NNB'), ('최선', 'NNP'), ('을', 'NNG'), ('다', 'MAG'), ('하', 'NNG'), ('아', 'IC'), ('이', 'MM'), ('멋', 'NNG'), ('지', 'NNB'), ('ㄴ', 'JX'), ('여행', 'NNG'), ('을', 'NNG'), ('만끽', 'NNP'), ('하', 'NNG'), ('늘', 'VV'), ('ㄴ', 'ETM'), ('것', 'NNB'), ('이', 'MM'), ('다', 'MAG')]


In [ ]:
hannanumTag = []
for token in hannanum_tokens:
  hannanumTag += hannanum.pos(token)
print(hannanumTag)

[('인생', 'N'), ('은', 'N'), ('모두', 'M'), ('가', 'J'), ('함께하', 'P'), ('어', 'E'), ('늘', 'P'), ('ㄴ', 'E'), ('여행', 'N'), ('이', 'M'), ('다', 'M'), ('.', 'S'), ('매일매일', 'M'), ('사', 'N'), ('늘', 'P'), ('ㄴ', 'E'), ('동안', 'N'), ('우리', 'N'), ('가', 'J'), ('하', 'I'), ('ㄹ', 'N'), ('수', 'N'), ('있', 'N'), ('늘', 'P'), ('ㄴ', 'E'), ('것', 'N'), ('은', 'N'), ('최선', 'N'), ('을', 'N'), ('다하', 'P'), ('어', 'E'), ('어', 'N'), ('이', 'M'), ('멋지', 'N'), ('ㄴ', 'N'), ('여행', 'N'), ('을', 'N'), ('만끽', 'N'), ('하', 'I'), ('늘', 'P'), ('ㄴ', 'E'), ('것', 'N'), ('이', 'M'), ('다', 'M')]


In [ ]:
oktTag = []
for token in okt_tokens:
  oktTag += okt.pos(token)
print(oktTag)

[('인생', 'Noun'), ('은', 'Noun'), ('모두', 'Noun'), ('가', 'Verb'), ('함께', 'Adverb'), ('하는', 'Verb'), ('여행', 'Noun'), ('이다', 'Josa'), ('.', 'Punctuation'), ('매', 'Noun'), ('일', 'Noun'), ('매일', 'Noun'), ('사는', 'Verb'), ('동안', 'Noun'), ('우리', 'Noun'), ('가', 'Verb'), ('할', 'Verb'), ('수', 'Noun'), ('있는', 'Adjective'), ('건', 'Noun'), ('최선', 'Noun'), ('을', 'Josa'), ('다해', 'Noun'), ('이', 'Noun'), ('멋진', 'Adjective'), ('여행', 'Noun'), ('을', 'Josa'), ('만끽', 'Noun'), ('하는', 'Verb'), ('것', 'Noun'), ('이다', 'Josa')]


In [ ]:
kkmaTag =[]
for token in kkma_tokens:
  kkmaTag += kkma.pos(token)
print(kkmaTag)

[('인생', 'NNG'), ('은', 'NNG'), ('모두', 'MAG'), ('가', 'NNG'), ('함께', 'MAG'), ('하', 'NNG'), ('늘', 'VA'), ('ㄴ', 'ETD'), ('여행', 'NNG'), ('이', 'NNG'), ('다', 'NNG'), ('.', 'SF'), ('매일', 'MAG'), ('매일', 'MAG'), ('살', 'NNG'), ('늘', 'VA'), ('ㄴ', 'ETD'), ('동안', 'NNG'), ('우리', 'NP'), ('가', 'NNG'), ('하', 'NNG'), ('ㄹ', 'NNG'), ('수', 'NNG'), ('있', 'VA'), ('늘', 'VA'), ('ㄴ', 'ETD'), ('것', 'NNB'), ('은', 'NNG'), ('최선', 'NNG'), ('을', 'NNG'), ('다하', 'VV'), ('어', 'NNG'), ('이', 'NNG'), ('멋지', 'VA'), ('ㄴ', 'NNG'), ('여행', 'NNG'), ('을', 'NNG'), ('만끽', 'NNG'), ('하', 'NNG'), ('늘', 'VA'), ('ㄴ', 'ETD'), ('것', 'NNB'), ('이', 'NNG'), ('다', 'NNG')]


### 3) 불용어처리
- 자연어 처리를 위해 불필요한 요소를 제거하는 작업
- 불필요한 품사를 제거하거나 불필요한 단어를 제거하는 작업으로 구성된다
- [품사정보](https://docs.google.com/spreadsheets/d/1OGAjUvalBuX-oZvZ_-9tEfYD2gQe7hTGsgUpiiBSXI8/edit#gid=0)

In [ ]:
from collections import Counter #Counter는 갯수를 세주는 함수이다

- 아래처럼 자주 나오는 단어들을 집계해보면, 불용어 목룍에 무엇을 추가해야하는지 알 수 있다

In [ ]:
Counter(oktTag).most_common()

[(('가', 'Verb'), 2),
 (('하는', 'Verb'), 2),
 (('여행', 'Noun'), 2),
 (('이다', 'Josa'), 2),
 (('을', 'Josa'), 2),
 (('인생', 'Noun'), 1),
 (('은', 'Noun'), 1),
 (('모두', 'Noun'), 1),
 (('함께', 'Adverb'), 1),
 (('.', 'Punctuation'), 1),
 (('매', 'Noun'), 1),
 (('일', 'Noun'), 1),
 (('매일', 'Noun'), 1),
 (('사는', 'Verb'), 1),
 (('동안', 'Noun'), 1),
 (('우리', 'Noun'), 1),
 (('할', 'Verb'), 1),
 (('수', 'Noun'), 1),
 (('있는', 'Adjective'), 1),
 (('건', 'Noun'), 1),
 (('최선', 'Noun'), 1),
 (('다해', 'Noun'), 1),
 (('이', 'Noun'), 1),
 (('멋진', 'Adjective'), 1),
 (('만끽', 'Noun'), 1),
 (('것', 'Noun'), 1)]

In [ ]:
stopPos = ['Determiner','Adverb','Conjunction','Josa','PreEomi','Eomi','Suffix','Punctuation',
           'Foreign','Alpha','Number','Unknown']
stopWord = []
word = []
for tag in oktTag:
  if tag[1] not in stopPos:
    if tag[0] not in stopWord:
      word.append(tag[0])
print(word)

['인생', '은', '모두', '가', '하는', '여행', '매', '일', '매일', '사는', '동안', '우리', '가', '할', '수', '있는', '건', '최선', '다해', '이', '멋진', '여행', '만끽', '하는', '것']


In [ ]:
print(okt_tokens)

['인생', '은', '모두', '가', '함께', '하는', '여행', '이다', '.', '매', '일', '매일', '사는', '동안', '우리', '가', '할', '수', '있는', '건', '최선', '을', '다해', '이', '멋진', '여행', '을', '만끽', '하는', '것', '이다']


## 3. 한글 텍스트 마이닝 실습
- [뉴스](https://www.yna.co.kr/view/AKR20200204081000017?section=it/it)에서 유의미한 단어를 추출해보자

### 1) 크롤링
- 뉴스 페이지의 텍스트를 크롤링해 가져온다

In [ ]:
import requests
from bs4 import BeautifulSoup as bs

In [ ]:
url = 'https://www.yna.co.kr/view/AKR20200204081000017?section=it/it'
page = requests.get(url)
content = bs(page.text, 'html.parser')

In [ ]:
news = content.find('div',class_='story-news article')
txt = news.find_all('p')

- 크롤링 했을 때, 공백이 함께 나오면 replace('\n','')를 활용해 공백을 삭제한다
- 위의 결과에서 tag를 떼고 하나의 Str을 만들기 위해 For문을 활용한다

In [ ]:
text = ''
for line in txt:
  text += line.text
text[:500]

'(서울=연합뉴스) 홍지인 기자 = 구글의 칼라 브롬버그 \'공익을 위한 AI\' 프로그램 리드가 4일 역삼동 구글코리아에서 화상 기자간담회를 갖고 있다. 2020. 2. 4. (서울=연합뉴스) 홍지인 기자 = 구글은 인공지능(AI) 기술을 활용한 기상 예측 모델을 개발해 일부 분야에서는 미국 정부보다 더 뛰어난 예보 결과를 내놓고 있다고 4일 밝혔다. 구글의 칼라 브롬버그 \'공익을 위한 AI\' 프로그램 리드는 이날 서울 역삼동 구글코리아에서 가진 화상 기자간담회에서 "신경망을 이용한 기상 예측은 기존 예측 방법보다 훨씬 정확하다"고 말했다.  구글의 \'나우캐스트\' 기상 예측 모델은 6시간 이내 단기 예보에 초점을 맞추고 기상 레이더 관측 자료와 위성 사진 등을 모아 유넷(U-Net)이라는 신경망으로 계산한다. 기존 모델로는 몇 시간이 걸리는 작업을 5~10분 만에 내놓을 수 있고, 공간 해상도도 1㎞로 미국 해양대기청(NOAA)의 예보모델 \'HRRR\'보다 10배 더 상세하다고 구글은 소'

### 2) 토큰화
- Mecab패키지를 import해 크롤링한 뉴스 텍스트의 토큰화를 진행한다
- 구글 코랩에서는 Mecab이 원활하게 작동하지 않기 때문에 코드를 중심으로 작성하도록 하겠다

In [ ]:
from konlpy.tag import Mecab

In [ ]:
!pip install Mecab
mecab = Mecab()
mecab_tokens = mecab.morphs(text)
print(mecab_tokens)

- 위의 결과는 다음과 같이 출력된다
``` python
['(', '서울', '=', '연합뉴스', ')', '홍지인', '기자', '=', '구글', '의', '칼라', '브롬버그', "'", '공익', '을', '위한', 'AI', "'", '프로그램', '리드', '가', '4', '일', '역삼동', '구글', '코리아', '에서', '화상', '기자', '간담회', '를', '갖', '고', '있', '다', '.', '2020', '.', '2', '.', '4', '.', '(', '서울', '=', '연합뉴스', ')', '홍지인', '기자', '=', '구글', '은', '인공지능', '(', 'AI', ')', '기술', '을', '활용', '한', '기상', '예측', '모델', '을', '개발', '해', '일부', '분야', '에서', '는', '미국', '정부', '보다', '더', '뛰어난', '예보', '결과', '를', '내놓', '고', '있', '다고', '4', '일', '밝혔', '다', '.', '구글', '의', '칼라', '브롬버그', "'", '공익', '을', '위한', 'AI', "'", '프로그램', '리드', '는', '이날', '서울', '역삼동', '구글', '코리아', '에서', '가진', '화상', '기자', '간담회', '에서', '"', '신경망', '을', '이용', '한', '기상', '예측', '은', '기존', '예측', '방법', '보다', '훨씬', '정확', '하', '다', '"', '고', '말', '했', '다', '.', '구글', '의', "'", '나우', '캐스트', "'", '기상', '예측', '모델', '은', '6', '시간', '이내', '단기', '예보', '에', '초점', '을', '맞추', '고', '기상', '레이더', '관측', '자료', '와', '위성', '사진', '등', '을', '모아', '유', '넷', '(', 'U', '-', 'Net', ')', '이', '라는', '신경망', '으로', '계산', '한다', '.', '기존', '모델', '로', '는', '몇', '시간', '이', '걸리', '는', '작업', '을', '5', '~', '10', '분', '만', '에', '내놓', '을', '수', '있', '고', ',', '공간', '해상도', '도', '1', '㎞', '로', '미국', '해양', '대', '기청', '(', 'NOAA', ')', '의', '예보', '모델', "'", 'HRRR', "'", '보다', '10', '배', '더', '상세', '하', '다고', '구글', '은', '소개', '했', '다', '.', '예보', '정확', '도', '면', '에서', '는', '1', '~', '3', '시간', '단기', '예보', '의', '경우', '도', 'HRRR', '보다', '더', '뛰어나', '다고', '구글', '은', '분석', '했', '다', '.', '단', ',', '5', '~', '6', '시간', '이상', '예보', '에서', '는', 'HRRR', '이', '더', '정확', '했', '다', '.', '칼라', '리드', '는', '"', '지금', '시점', '에서', '당장', '기상', '예측', '모델', '을', '상용', '화', '할', '계획', '은', '없', '다', '"', '며', '"', '머신', '러닝', '기법', '을', '이용', '해', '얼마나', '날씨', '를', '정확', '하', '게', '예측', '할', '수', '있', '는지', '에', '대해', '연구', '과제', '로', '만', '삼', '고', '있', '다', '"', '고', '말', '했', '다', '.', '함유근', '전', '남대', '지구', '환경', '과', '학부', '교수', '는', '이날', '간담회', '에서', "'", '합성곱', '신경망', '기법', "'(", 'CNN', '·', 'Convolutional', 'Neural', 'Network', ')', '을', '응용', '한', '엘니뇨', '예측', '모형', '을', '소개', '했', '다', '.', '그', '가', '개발', '한', '엘니뇨', '예측', '모형', '은', '향후', '18', '개월', '동안', '70', '%', '이상', '정확도', '로', '엘니뇨', '발생', '가능', '성', '을', '맞출', '수', '있', '다', '.', '기존', '모델', '은', '예능', '가능', '기간', '이', '1', '년', '정도', '였', '다고', '함', '교수', '는', '소개', '했', '다', '.', '함', '교수', '는', '"', '엘니뇨', '의', '예측', '성능', '이', '18', '개월', '로', '늘어나', '면', '엘니뇨', '로', '인해', '발생', '하', '는', '전', '세계', '적', '인', '곡물', '가격', '변동', '등', '에', '선제', '적', '으로', '대응', '할', '수', '있', '게', '된다', '"', '고', '설명', '했', '다', '.', 'ljungberg', '@', 'yna', '.', 'co', '.', 'kr', '<', '저작권자', '(', 'c', ')', '연합뉴스', ',', '무단', '전재', '-', '재', '배포', '금지', '>', '2020', '/', '02', '/', '04', '11', ':', '33', '송고']
```

### 3) 품사 부착
- 토큰화한 단어에 품사를 부착한다

In [ ]:
mecabTag=[]
for token in mecab_tokens:
    mecabTag += mecab.pos(token)
print(mecabTag)

- 위의 결과는 다음과 같다
``` python
[('(', 'SSO'), ('서울', 'NNP'), ('=', 'SY'), ('연합뉴스', 'NNP'), (')', 'SSC'), ('홍지인', 'NNP'), ('기자', 'NNG'), ('=', 'SY'), ('구글', 'NNG'), ('의', 'NNG'), ('칼라', 'NNG'), ('브롬버그', 'NNP'), ("'", 'SY'), ('공익', 'NNG'), ('을', 'JKO'), ('위한', 'VV+ETM'), ('AI', 'SL'), ("'", 'SY'), ('프로그램', 'NNG'), ('리드', 'NNP'), ('가', 'VV+EC'), ('4', 'SN'), ('일', 'NNG'), ('역삼동', 'NNP'), ('구글', 'NNG'), ('코리아', 'NNP'), ('에서', 'JKB'), ('화상', 'NNG'), ('기자', 'NNG'), ('간담회', 'NNG'), ('를', 'JKO'), ('갖', 'NNG'), ('고', 'EC'), ('있', 'VA'), ('다', 'MAG'), ('.', 'SF'), ('2020', 'SN'), ('.', 'SF'), ('2', 'SN'), ('.', 'SF'), ('4', 'SN'), ('.', 'SF'), ('(', 'SSO'), ('서울', 'NNP'), ('=', 'SY'), ('연합뉴스', 'NNP'), (')', 'SSC'), ('홍지인', 'NNP'), ('기자', 'NNG'), ('=', 'SY'), ('구글', 'NNG'), ('은', 'NNG'), ('인공지능', 'NNP'), ('(', 'SSO'), ('AI', 'SL'), (')', 'SSC'), ('기술', 'NNG'), ('을', 'JKO'), ('활용', 'NNG'), ('한', 'MM'), ('기상', 'NNG'), ('예측', 'NNG'), ('모델', 'NNG'), ('을', 'JKO'), ('개발', 'NNG'), ('해', 'VV+EC'), ('일부', 'NNG'), ('분야', 'NNG'), ('에서', 'JKB'), ('는', 'JX'), ('미국', 'NNP'), ('정부', 'NNG'), ('보', 'VV'), ('다', 'EC'), ('더', 'MAG'), ('뛰어난', 'VA+ETM'), ('예보', 'NNG'), ('결과', 'NNG'), ('를', 'JKO'), ('내', 'NP+JKG'), ('놓', 'NNG'), ('고', 'EC'), ('있', 'VA'), ('다고', 'EC'), ('4', 'SN'), ('일', 'NNG'), ('밝혔', 'VV+EP'), ('다', 'MAG'), ('.', 'SF'), ('구글', 'NNG'), ('의', 'NNG'), ('칼라', 'NNG'), ('브롬버그', 'NNP'), ("'", 'SY'), ('공익', 'NNG'), ('을', 'JKO'), ('위한', 'VV+ETM'), ('AI', 'SL'), ("'", 'SY'), ('프로그램', 'NNG'), ('리드', 'NNP'), ('는', 'JX'), ('이날', 'NNG'), ('서울', 'NNP'), ('역삼동', 'NNP'), ('구글', 'NNG'), ('코리아', 'NNP'), ('에서', 'JKB'), ('가진', 'VV+ETM'), ('화상', 'NNG'), ('기자', 'NNG'), ('간담회', 'NNG'), ('에서', 'JKB'), ('"', 'SY'), ('신경망', 'NNG'), ('을', 'JKO'), ('이용', 'NNG'), ('한', 'MM'), ('기상', 'NNG'), ('예측', 'NNG'), ('은', 'NNG'), ('기존', 'NNG'), ('예측', 'NNG'), ('방법', 'NNG'), ('보', 'VV'), ('다', 'EC'), ('훨씬', 'MAG'), ('정확', 'NNG'), ('하', 'VV'), ('다', 'MAG'), ('"', 'SY'), ('고', 'EC'), ('말', 'NNG'), ('했', 'VV+EP'), ('다', 'MAG'), ('.', 'SF'), ('구글', 'NNG'), ('의', 'NNG'), ("'", 'SY'), ('나우', 'NNP'), ('캐스트', 'NNG'), ("'", 'SY'), ('기상', 'NNG'), ('예측', 'NNG'), ('모델', 'NNG'), ('은', 'NNG'), ('6', 'SN'), ('시간', 'NNG'), ('이내', 'NNG'), ('단기', 'NNG'), ('예보', 'NNG'), ('에', 'IC'), ('초점', 'NNG'), ('을', 'JKO'), ('맞추', 'VV'), ('고', 'EC'), ('기상', 'NNG'), ('레이더', 'NNG'), ('관측', 'NNG'), ('자료', 'NNG'), ('와', 'VV+EC'), ('위성', 'NNG'), ('사진', 'NNG'), ('등', 'NNG'), ('을', 'JKO'), ('모아', 'VV+EC'), ('유', 'NNP'), ('넷', 'NR'), ('(', 'SSO'), ('U', 'SL'), ('-', 'SY'), ('Net', 'SL'), (')', 'SSC'), ('이', 'MM'), ('라는', 'ETM'), ('신경망', 'NNG'), ('으로', 'JKB'), ('계산', 'NNG'), ('한다', 'VV+EC'), ('.', 'SF'), ('기존', 'NNG'), ('모델', 'NNG'), ('로', 'JKB'), ('는', 'JX'), ('몇', 'MM'), ('시간', 'NNG'), ('이', 'MM'), ('걸리', 'NNG'), ('는', 'JX'), ('작업', 'NNG'), ('을', 'JKO'), ('5', 'SN'), ('~', 'SY'), ('10', 'SN'), ('분', 'NNG'), ('만', 'JX'), ('에', 'IC'), ('내', 'NP+JKG'), ('놓', 'NNG'), ('을', 'JKO'), ('수', 'NNG'), ('있', 'VA'), ('고', 'EC'), (',', 'SC'), ('공간', 'NNG'), ('해상도', 'NNG'), ('도', 'NNG'), ('1', 'SN'), ('㎞', 'SY'), ('로', 'JKB'), ('미국', 'NNP'), ('해양', 'NNG'), ('대', 'NNG'), ('기청', 'NNG'), ('(', 'SSO'), ('NOAA', 'SL'), (')', 'SSC'), ('의', 'NNG'), ('예보', 'NNG'), ('모델', 'NNG'), ("'", 'SY'), ('HRRR', 'SL'), ("'", 'SY'), ('보', 'VV'), ('다', 'EC'), ('10', 'SN'), ('배', 'NNG'), ('더', 'MAG'), ('상세', 'NNG'), ('하', 'VV'), ('다고', 'EC'), ('구글', 'NNG'), ('은', 'NNG'), ('소개', 'NNG'), ('했', 'VV+EP'), ('다', 'MAG'), ('.', 'SF'), ('예보', 'NNG'), ('정확', 'NNG'), ('도', 'NNG'), ('면', 'NNG'), ('에서', 'JKB'), ('는', 'JX'), ('1', 'SN'), ('~', 'SY'), ('3', 'SN'), ('시간', 'NNG'), ('단기', 'NNG'), ('예보', 'NNG'), ('의', 'NNG'), ('경우', 'NNG'), ('도', 'NNG'), ('HRRR', 'SL'), ('보', 'VV'), ('다', 'EC'), ('더', 'MAG'), ('뛰어나', 'VA+EC'), ('다고', 'EC'), ('구글', 'NNG'), ('은', 'NNG'), ('분석', 'NNG'), ('했', 'VV+EP'), ('다', 'MAG'), ('.', 'SF'), ('단', 'MM'), (',', 'SC'), ('5', 'SN'), ('~', 'SY'), ('6', 'SN'), ('시간', 'NNG'), ('이상', 'NNG'), ('예보', 'NNG'), ('에서', 'JKB'), ('는', 'JX'), ('HRRR', 'SL'), ('이', 'MM'), ('더', 'MAG'), ('정확', 'NNG'), ('했', 'VV+EP'), ('다', 'MAG'), ('.', 'SF'), ('칼라', 'NNG'), ('리드', 'NNP'), ('는', 'JX'), ('"', 'SY'), ('지금', 'NNG'), ('시점', 'NNG'), ('에서', 'JKB'), ('당장', 'NNG'), ('기상', 'NNG'), ('예측', 'NNG'), ('모델', 'NNG'), ('을', 'JKO'), ('상용', 'NNG'), ('화', 'NNG'), ('할', 'VV+ETM'), ('계획', 'NNG'), ('은', 'NNG'), ('없', 'VA'), ('다', 'MAG'), ('"', 'SY'), ('며', 'EC'), ('"', 'SY'), ('머신', 'NNG'), ('러닝', 'NNG'), ('기법', 'NNG'), ('을', 'JKO'), ('이용', 'NNG'), ('해', 'VV+EC'), ('얼마나', 'MAG'), ('날씨', 'NNG'), ('를', 'JKO'), ('정확', 'NNG'), ('하', 'VV'), ('게', 'NNG'), ('예측', 'NNG'), ('할', 'VV+ETM'), ('수', 'NNG'), ('있', 'VA'), ('는지', 'EC'), ('에', 'IC'), ('대해', 'VV+EC'), ('연구', 'NNG'), ('과제', 'NNG'), ('로', 'JKB'), ('만', 'JX'), ('삼', 'NR'), ('고', 'EC'), ('있', 'VA'), ('다', 'MAG'), ('"', 'SY'), ('고', 'EC'), ('말', 'NNG'), ('했', 'VV+EP'), ('다', 'MAG'), ('.', 'SF'), ('함유근', 'NNP'), ('전', 'NNG'), ('남대', 'NNG'), ('지구', 'NNG'), ('환경', 'NNG'), ('과', 'NNG'), ('학부', 'NNG'), ('교수', 'NNG'), ('는', 'JX'), ('이날', 'NNG'), ('간담회', 'NNG'), ('에서', 'JKB'), ("'", 'SY'), ('합성곱', 'NNP'), ('신경망', 'NNG'), ('기법', 'NNG'), ("'(", 'SY'), ('CNN', 'SL'), ('·', 'SC'), ('Convolutional', 'SL'), ('Neural', 'SL'), ('Network', 'SL'), (')', 'SSC'), ('을', 'JKO'), ('응용', 'NNG'), ('한', 'MM'), ('엘니뇨', 'NNG'), ('예측', 'NNG'), ('모형', 'NNG'), ('을', 'JKO'), ('소개', 'NNG'), ('했', 'VV+EP'), ('다', 'MAG'), ('.', 'SF'), ('그', 'MM'), ('가', 'VV+EC'), ('개발', 'NNG'), ('한', 'MM'), ('엘니뇨', 'NNG'), ('예측', 'NNG'), ('모형', 'NNG'), ('은', 'NNG'), ('향후', 'NNG'), ('18', 'SN'), ('개월', 'NNBC'), ('동안', 'NNG'), ('70', 'SN'), ('%', 'SY'), ('이상', 'NNG'), ('정확도', 'NNG'), ('로', 'JKB'), ('엘니뇨', 'NNG'), ('발생', 'NNG'), ('가능', 'NNG'), ('성', 'NNG'), ('을', 'JKO'), ('맞출', 'VV+ETM'), ('수', 'NNG'), ('있', 'VA'), ('다', 'MAG'), ('.', 'SF'), ('기존', 'NNG'), ('모델', 'NNG'), ('은', 'NNG'), ('예능', 'NNG'), ('가능', 'NNG'), ('기간', 'NNG'), ('이', 'MM'), ('1', 'SN'), ('년', 'NNG'), ('정도', 'NNG'), ('였', 'EP'), ('다고', 'EC'), ('함', 'NNG'), ('교수', 'NNG'), ('는', 'JX'), ('소개', 'NNG'), ('했', 'VV+EP'), ('다', 'MAG'), ('.', 'SF'), ('함', 'NNG'), ('교수', 'NNG'), ('는', 'JX'), ('"', 'SY'), ('엘니뇨', 'NNG'), ('의', 'NNG'), ('예측', 'NNG'), ('성능', 'NNG'), ('이', 'MM'), ('18', 'SN'), ('개월', 'NNBC'), ('로', 'JKB'), ('늘어나', 'VV+EC'), ('면', 'NNG'), ('엘니뇨', 'NNG'), ('로', 'JKB'), ('인해', 'VV+EC'), ('발생', 'NNG'), ('하', 'VV'), ('는', 'JX'), ('전', 'NNG'), ('세계', 'NNG'), ('적', 'NNG'), ('인', 'NNG'), ('곡물', 'NNG'), ('가격', 'NNG'), ('변동', 'NNG'), ('등', 'NNG'), ('에', 'IC'), ('선제', 'NNG'), ('적', 'NNG'), ('으로', 'JKB'), ('대응', 'NNG'), ('할', 'VV+ETM'), ('수', 'NNG'), ('있', 'VA'), ('게', 'NNG'), ('된다', 'VV+EC'), ('"', 'SY'), ('고', 'EC'), ('설명', 'NNG'), ('했', 'VV+EP'), ('다', 'MAG'), ('.', 'SF'), ('ljungberg', 'SL'), ('@', 'SY'), ('yna', 'SL'), ('.', 'SF'), ('co', 'SL'), ('.', 'SF'), ('kr', 'SL'), ('<', 'SY'), ('저작권자', 'NNG'), ('(', 'SSO'), ('c', 'SL'), (')', 'SSC'), ('연합뉴스', 'NNP'), (',', 'SC'), ('무단', 'NNG'), ('전재', 'NNG'), ('-', 'SY'), ('재', 'XPN'), ('배포', 'NNG'), ('금지', 'NNG'), ('>', 'SY'), ('2020', 'SN'), ('/', 'SC'), ('02', 'SN'), ('/', 'SC'), ('04', 'SN'), ('11', 'SN'), (':', 'SC'), ('33', 'SN'), ('송고', 'NNP')]
```

### 4) 불용어 처리
- Counter를 이용해 문장을 구성하는 단어와 품사를 살펴본 뒤 불용어를 선택해 필터링한다

In [ ]:
from collections import Counter
Counter(mecabTag).most_common()

In [ ]:
stopPos = ['SF','JKO','JX','SY','JKB','EC','EP','SSO','SSC','SN','SC',
           'SL', 'JKS','JKC','JKG','JKB','JC','VV+EC','IC']
stopWord = ['연합뉴스','홍지인','저작권자','기자','무단','전재','재','배포',
            '금지','의','이','다','있','에','과','은','도','하','수','보','더',
           '게','등']
word = []
for tag in mecabTag:
    if tag[1] not in stopPos:
        if tag[0] not in stopWord:
              word.append(tag[0])
print(word)

- 위의 과정을 끝내면 다음과 같은 단어 목록을 얻을 수 있다
``` python
['서울', '구글', '칼라', '브롬버그', '공익', '위한', '프로그램', '리드', '일', '역삼동', '구글', '코리아', '화상', '간담회', '갖', '서울', '구글', '인공지능', '기술', '활용', '한', '기상', '예측', '모델', '개발', '일부', '분야', '미국', '정부', '뛰어난', '예보', '결과', '내', '놓', '일', '밝혔', '구글', '칼라', '브롬버그', '공익', '위한', '프로그램', '리드', '이날', '서울', '역삼동', '구글', '코리아', '가진', '화상', '간담회', '신경망', '이용', '한', '기상', '예측', '기존', '예측', '방법', '훨씬', '정확', '말', '했', '구글', '나우', '캐스트', '기상', '예측', '모델', '시간', '이내', '단기', '예보', '초점', '맞추', '기상', '레이더', '관측', '자료', '위성', '사진', '유', '넷', '라는', '신경망', '계산', '기존', '모델', '몇', '시간', '걸리', '작업', '분', '내', '놓', '공간', '해상도', '미국', '해양', '대', '기청', '예보', '모델', '배', '상세', '구글', '소개', '했', '예보', '정확', '면', '시간', '단기', '예보', '경우', '뛰어나', '구글', '분석', '했', '단', '시간', '이상', '예보', '정확', '했', '칼라', '리드', '지금', '시점', '당장', '기상', '예측', '모델', '상용', '화', '할', '계획', '없', '머신', '러닝', '기법', '이용', '얼마나', '날씨', '정확', '예측', '할', '연구', '과제', '삼', '말', '했', '함유근', '전', '남대', '지구', '환경', '학부', '교수', '이날', '간담회', '합성곱', '신경망', '기법', '응용', '한', '엘니뇨', '예측', '모형', '소개', '했', '그', '개발', '한', '엘니뇨', '예측', '모형', '향후', '개월', '동안', '이상', '정확도', '엘니뇨', '발생', '가능', '성', '맞출', '기존', '모델', '예능', '가능', '기간', '년', '정도', '함', '교수', '소개', '했', '함', '교수', '엘니뇨', '예측', '성능', '개월', '면', '엘니뇨', '발생', '전', '세계', '적', '인', '곡물', '가격', '변동', '선제', '적', '대응', '할', '설명', '했', '송고']
```

## 4. 단어의 표현
- 단어를 인코딩할 수 있는 다양한 방법을 알아보자

### 1) 원핫인코딩

#### 1) For문을 활용한 인코딩

In [ ]:
word_ls = ['원숭이','바나나','사과','코끼리']

In [ ]:
from collections import defaultdict
import numpy as np

word2id_dic = defaultdict(lambda:len(word2id_dic))
for word in word_ls:
  word2id_dic[word]
print(word2id_dic)

defaultdict(<function <lambda> at 0x7f2c34d4ac80>, {'원숭이': 0, '바나나': 1, '사과': 2, '코끼리': 3})


In [ ]:
n_unique_words = len(word2id_dic) #4겠지
one_hot_vectors = np.zeros((len(word_ls),n_unique_words))
one_hot_vectors

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
for i, word in enumerate(word_ls):
  index = word2id_dic[word]
  one_hot_vectors[i,index] += 1
one_hot_vectors

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### 2) 라이브러리를 활용한 인코딩

In [ ]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

values = array(word_ls)
values

array(['원숭이', '바나나', '사과', '코끼리'], dtype='<U3')

In [ ]:
label_enc = LabelEncoder()
int_enc = label_enc.fit_transform(values)
int_enc

array([2, 0, 1, 3])

In [ ]:
onehot_enc = OneHotEncoder(sparse=False)
int_enc = int_enc.reshape(len(int_enc), 1)
onehot_enc = onehot_enc.fit_transform(int_enc)
onehot_enc

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

### 2) BOW(Bag of Words)
- 출현빈도수로 단어를 표현하는 방법

#### 1) 인덱스 부여

In [ ]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
        '오늘 동물원에서 원숭이에게 사과를 줬어']

In [ ]:
doc_ls = []
for doc in docs:
  doc_ls.append(doc.split(' '))
doc_ls

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'],
 ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]

In [ ]:
from collections import defaultdict
word2id = defaultdict(lambda : len(word2id))
word2id

defaultdict(<function __main__.<lambda>>, {})

In [ ]:
for doc in doc_ls:
  for token in doc:
    word2id[token]
word2id

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '먹이를': 6,
             '보고': 4,
             '사과를': 8,
             '오늘': 0,
             '원숭이를': 3,
             '원숭이에게': 5,
             '줬어': 7,
             '코끼리': 2})

#### 2) 빈도 수 파악

In [ ]:
import numpy as np
BoW_ls = []
for i, doc in enumerate(doc_ls):
  bow = np.zeros(len(word2id),dtype=int)
  print(bow)
  for token in doc:
    bow[word2id[token]] += 1 #토큰의 위치가 같으면
  BoW_ls.append(bow.tolist())
BoW_ls

[0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

#### 3) 시각화

In [ ]:
from IPython.core import display as ICD
import pandas as pd
sorted_vocab = sorted((value,key) for key, value in word2id.items())
print('sorted_vocab',sorted_vocab)

sorted_vocab [(0, '오늘'), (1, '동물원에서'), (2, '코끼리'), (3, '원숭이를'), (4, '보고'), (5, '원숭이에게'), (6, '먹이를'), (7, '줬어'), (8, '사과를')]


In [ ]:
vocab = []
for v in sorted_vocab:
  vocab.append(v[1])
print('vocab',vocab)

vocab ['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '원숭이에게', '먹이를', '줬어', '사과를']


In [ ]:
for i in range(len(docs)):
  print("문서{} : {}".format(i,docs[i]))
  ICD.display(pd.DataFrame([BoW_ls[i]], columns=vocab))
  print("\n\n")

문서0 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    2     1   1      1    1   1    0




문서1 : 오늘 동물원에서 원숭이에게 사과를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    0     0   0      1    0   1    1

#### 4) BOW실습

In [ ]:
docs = ['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해',
        '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [ ]:
doc_ls = []
for doc in docs: #문장을 구분해서 띄어쓰기 단위로 split진행
  doc_ls.append(doc.split(' '))
doc_ls

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [ ]:
from collections import defaultdict
word2id = defaultdict(lambda : len(word2id)) #들어온 리스트의 길이만큼 딕셔너리를 만드는 word2id생성
word2id

defaultdict(<function __main__.<lambda>>, {})

- [Defaultdict](https://www.geeksforgeeks.org/defaultdict-in-python/)은 기본 키값을 제공한다는 점에서 일반 Dict과 차이가 있다
- The functionality of both dictionaries and defualtdict are almost same except for the fact that defualtdict never raises a KeyError. 
- It provides a default value for the key that does not exists.

In [ ]:
for doc in doc_ls: #split된 것을 한 문장 단위로 추출
  for token in doc: #한 문장 내에서 끊어진 토큰들을 추출
    word2id[token]
word2id

defaultdict(<function __main__.<lambda>>,
            {'나는': 0,
             '싫어해': 6,
             '양념': 1,
             '좋아해': 3,
             '치킨을': 2,
             '하지만': 4,
             '후라이드': 5})

In [ ]:
import numpy as np
BoW_ls = []
for i, doc in enumerate(doc_ls): #문장 2개에 대하여
  bow = np.zeros(len(word2id),dtype=int) #생성된 인덱스 수에 맞게 0이 들어간 리스트 생성
  print(bow)
  for token in doc: #각문장의 토큰에 대해
    bow[word2id[token]] += 1 #토큰의 위치가 같으면
  BoW_ls.append(bow)
BoW_ls

[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]


[array([1, 1, 2, 1, 1, 1, 1]), array([1, 1, 2, 1, 1, 1, 1])]

In [ ]:
import numpy as np
BoW_ls = []
for i, doc in enumerate(doc_ls): #문장 2개에 대하여
  bow = np.zeros(len(word2id),dtype=int) #생성된 인덱스 수에 맞게 0이 들어간 리스트 생성
  print(bow)
  for token in doc: #각문장의 토큰에 대해
    bow[word2id[token]] += 1 #토큰의 위치가 같으면
  BoW_ls.append(bow.tolist()) #array를 하나의 리스트로 합치기 위해 tolist사용
BoW_ls

[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1], [1, 1, 2, 1, 1, 1, 1]]

#### 5) Sklearn을 활용한 BOW생성

In [ ]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
        '오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어\
        오늘 동물원에서 원숭이에게 사과를 줬어']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()
BoW = count_vect.fit_transform(docs) #Sklearn은 토큰이 아니라 전체 문장을 입력값으로 받는다
print(BoW.toarray())
vocab = count_vect.get_feature_names()
print(vocab)

[[1 1 1 0 1 1 1 1 2]
 [2 1 1 1 2 1 2 2 2]]
['동물원에서', '먹이를', '보고', '사과를', '오늘', '원숭이를', '원숭이에게', '줬어', '코끼리']


In [ ]:
from IPython.core import display as ICD
import pandas as pd

for i in range(len(docs)):
  print("문서{} : {}".format(i,docs[i]))
  ICD.display(pd.DataFrame([BoW.toarray()[i]], columns=vocab))
  print("\n\n")

문서0 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      1    1   1    0   1     1      1   1    2




문서1 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어        오늘 동물원에서 원숭이에게 사과를 줬어


동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      2    1   1    1   2     1      2   2    2

#### 6) Gensim을 활용한 BOW생성

In [ ]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
        '오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어\
        오늘 동물원에서 원숭이에게 사과를 줬어']

In [ ]:
from gensim import corpora
doc_ls = []
for doc in docs: 
  doc_ls.append(doc.split(' '))

In [ ]:
doc_ls

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'],
 ['오늘',
  '동물원에서',
  '코끼리',
  '원숭이를',
  '보고',
  '코끼리',
  '원숭이에게',
  '먹이를',
  '줬어',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '오늘',
  '동물원에서',
  '원숭이에게',
  '사과를',
  '줬어']]

In [ ]:
id2word = corpora.Dictionary(doc_ls) #Gensim은 토큰화된 단어들을 입력값으로 받는다
BoW = []
for doc in doc_ls:
  BoW.append(id2word.doc2bow(doc)) 
BoW

[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 2)],
 [(0, 2),
  (1, 1),
  (2, 1),
  (3, 2),
  (4, 1),
  (5, 2),
  (6, 2),
  (7, 2),
  (8, 7),
  (9, 1)]]

In [ ]:
from gensim.matutils import sparse2full
from IPython.core import display as ICD
import pandas as pd

vocab = [id2word[i] for i in id2word.keys()]
for i in range(len(docs)):
  print("문서{} : {}".format(i,docs[i]))
  ICD.display(pd.DataFrame([sparse2full(BoW[0],len(vocab))], columns=vocab))
  print("\n\n")

문서0 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


동물원에서  먹이를   보고   오늘  원숭이를  원숭이에게   줬어  코끼리       사과를
0    1.0  1.0  1.0  1.0   1.0    1.0  1.0  2.0  0.0  0.0




문서1 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어        오늘 동물원에서 원숭이에게 사과를 줬어


동물원에서  먹이를   보고   오늘  원숭이를  원숭이에게   줬어  코끼리       사과를
0    1.0  1.0  1.0  1.0   1.0    1.0  1.0  2.0  0.0  0.0

### 3) DTM/TDM 
- DTM과 TDM은 모두 BOW와 비슷하나 행렬개념이 추가된 것이다
  + DTM(Document-Term Matrix)
  + TDM(Term-Document Matrix)
- 토큰화, Index추출, 빈도수를 계산
- BOW와 마찬가지로 단어의 순서를 고려하지 않으며 빈도수가 중요도를 나타내지 못한다는 한계가 있다


#### 1) 인덱스 부여

In [ ]:
docs = ['동물원 코끼리',
        '동물원 원숭이 바나나',
        '엄마 코끼리 아기 코끼리',
        '원숭이 바나나 코끼리 바나나']

In [ ]:
doc_ls = []
for doc in docs:
  doc_ls.append(doc.split(' '))
doc_ls

[['동물원', '코끼리'],
 ['동물원', '원숭이', '바나나'],
 ['엄마', '코끼리', '아기', '코끼리'],
 ['원숭이', '바나나', '코끼리', '바나나']]

In [ ]:
from collections import defaultdict
word2id = defaultdict(lambda: len(word2id))
for doc in doc_ls:
  for token in doc:
    word2id[token]
word2id

defaultdict(<function __main__.<lambda>>,
            {'동물원': 0, '바나나': 3, '아기': 5, '엄마': 4, '원숭이': 2, '코끼리': 1})

#### 2) 빈도 수 파악_행렬

In [ ]:
import numpy as np
TDM = np.zeros((len(word2id), len(doc_ls)),dtype=int)
print(TDM)
for i, doc in enumerate(doc_ls):
  for token in doc:
    TDM[word2id[token],i] += 1 #BOW와 달리 하나의 array형태로 표시
TDM

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


array([[1, 1, 0, 0],
       [1, 0, 2, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 0]])

#### 4) 시각화

In [ ]:
import pandas as pd

doc_names = ['문서'+str(i) for i in range(len(doc_ls))]
sorted_vocab = sorted((value,key) for key,value in word2id.items())
vocab = [v[1] for v in sorted_vocab]
df_TDM = pd.DataFrame(TDM, columns = doc_names)
df_TDM['단어'] = vocab
df_TDM.set_index('단어')

문서0  문서1  문서2  문서3
단어                     
동물원    1    1    0    0
코끼리    1    0    2    1
원숭이    0    1    0    1
바나나    0    1    0    2
엄마     0    0    1    0
아기     0    0    1    0

#### 5) Sklearn을 활용한 TDM 생성

In [ ]:
docs = ['동물원 코끼리',
        '동물원 원숭이 바나나',
        '엄마 코끼리 아기 코끼리',
        '원숭이 바나나 코끼리 바나나']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
DTM = count_vect.fit_transform(docs)
DTM.toarray()

array([[1, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 1, 0],
       [0, 0, 1, 1, 0, 2],
       [0, 2, 0, 0, 1, 1]])

In [ ]:
DTM.toarray().T

array([[1, 1, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 2, 1]])

In [ ]:
import pandas as pd

doc_names = ['문서'+str(i) for i in range(len(doc_ls))]
vocab = count_vect.get_feature_names()
df_TDM = pd.DataFrame(DTM.toarray().T, columns=doc_names)
df_TDM['단어'] = vocab
df_TDM.set_index('단어')

문서0  문서1  문서2  문서3
단어                     
동물원    1    1    0    0
바나나    0    1    0    2
아기     0    0    1    0
엄마     0    0    1    0
원숭이    0    1    0    1
코끼리    1    0    2    1

#### 6) Gensim을 활용한 TDM 생성

In [ ]:
docs = ['동물원 코끼리',
        '동물원 원숭이 바나나',
        '엄마 코끼리 아기 코끼리',
        '원숭이 바나나 코끼리 바나나']

In [ ]:
import gensim
from gensim import corpora
doc_ls = [doc.split() for doc in docs]

id2word = corpora.Dictionary(doc_ls)
TDM = [id2word.doc2bow(doc) for doc in doc_ls]
TDM

[[(0, 1), (1, 1)],
 [(0, 1), (2, 1), (3, 1)],
 [(1, 2), (4, 1), (5, 1)],
 [(1, 1), (2, 2), (3, 1)]]

In [ ]:
from gensim.matutils import sparse2full
import pandas as pd
import numpy as np

doc_names = ['문서'+str(i) for i in range(len(doc_ls))]
vocab = [id2word[1] for i in id2word.keys()]
DTM_matrix = [sparse2full(doc, len(vocab)).tolist() for doc in TDM]
df_TDM = pd.DataFrame(np.array(DTM_matrix, dtype=int).T,
                      columns = doc_names)
df_TDM['단어'] = vocab
df_TDM.set_index('단어')

문서0  문서1  문서2  문서3
단어                     
코끼리    1    1    0    0
코끼리    1    0    2    1
코끼리    0    1    0    2
코끼리    0    1    0    1
코끼리    0    0    1    0
코끼리    0    0    1    0

### 4) TF-IDF
- 단어빈도-역문서빈도
  + TF = 한 문서 내에서 단어가 얼마나 많이 등장했는가
    + 특정 단어 등장 빈도/문서 내 전체 등장 단어 빈도로 계산
  + IDF = 단어가 몇 개의 문서에 등장했는지를 계산 한 후 역수로 전환
    + log(총 문서수/단어가 등장한 문자수)
    + 로그값을 취해주는 이유 = 등장한 문자수 간의 유의미한 차이만을 반영하기 위해서

- TF*IDF값이 클 수록 문서 내 단어의 중요도가 크다고 할 수 있다


#### 1) 인덱스 부여

In [ ]:
docs = ['오늘 동물원에서 원숭이와 코끼리를 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [ ]:
doc_ls=[]
for doc in docs:
  doc_ls.append(doc.split())
doc_ls

[['오늘', '동물원에서', '원숭이와', '코끼리를', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [ ]:
from collections import defaultdict
word2id = defaultdict(lambda : len(word2id)) #들어온 리스트의 길이만큼 딕셔너리를 만드는 word2id생성
word2id
for doc in doc_ls: #split된 것을 한 문장 단위로 추출
  for token in doc: #한 문장 내에서 끊어진 토큰들을 추출
    word2id[token]
word2id

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '바나나를': 6,
             '봤어': 4,
             '오늘': 0,
             '원숭이에게': 5,
             '원숭이와': 2,
             '줬어': 7,
             '코끼리를': 3})

In [ ]:
import numpy as np

DTM = np.zeros((len(doc_ls),len(word2id)), dtype=int)
print(TDM)
for i, doc in enumerate(doc_ls):
  for token in doc:
    DTM[i,word2id[token]] += 1 
DTM

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


array([[1, 1, 1, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 2, 1]])

#### 2) TF계산

In [ ]:
def computeTF(DTM):
  doc_len = len(DTM)
  word_len = len(DTM[0])
  tf = np.zeros((doc_len, word_len))
  print(tf)
  for doc_i in range(doc_len):
      for word_i in range(word_len) :
        tf[doc_i,word_i] = DTM[doc_i,word_i]/DTM[doc_i].sum()
  return tf

In [ ]:
computeTF(TDM)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


array([[0.2, 0.2, 0.2, 0.2, 0.2, 0. , 0. , 0. ],
       [0. , 0.2, 0. , 0. , 0. , 0.2, 0.4, 0.2]])

#### 3) IDF계산

In [ ]:
import math
def computeIDF(TDM):
  doc_len = len(TDM)
  word_len = len(TDM[0])  

  idf = np.zeros(word_len)

  for i in range(word_len) :
    idf[i] = math.log10(doc_len / np.count_nonzero(TDM[:,i]))
  return idf

In [ ]:
computeIDF(TDM)

array([0.30103, 0.     , 0.30103, 0.30103, 0.30103, 0.30103, 0.30103,
       0.30103])

#### 4) TF-IDF 계산

In [ ]:
def computeTFIDF(TDM):
  tf = computeTF(TDM)
  idf = computeIDF(TDM)
  tfidf = np.zeros(tf.shape)
  for doc_i in range(tf.shape[0]):
    for word_i in range(tf.shape[i]):
      tfidf[doc_i,word_i] = tf[doc_i,word_i] * idf[word_i]
  return tfidf

In [ ]:
import pandas as pd

sorted_vocab = sorted((value, key) for key, value in word2id.items())
vocab = [v[i] for v in sorted_vocab]
tfidf = computeTFIDF(TDM)
pd.DataFrame(tfidf,columns=vocab)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


오늘  동물원에서      원숭이와      코끼리를        봤어     원숭이에게      바나나를        줬어
0  0.060206    0.0  0.060206  0.060206  0.060206  0.000000  0.000000  0.000000
1  0.000000    0.0  0.000000  0.000000  0.000000  0.060206  0.120412  0.060206

#### 5) Sklearn을 활용한 TF-IDF 생성

In [ ]:
docs = ['오늘 동물원에서 원숭이와 코끼리를 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

from sklearn.feature_extraction.text import TfidfVectorizer
tfidv = TfidfVectorizer()
tfidv = tfidv.fit(docs)
tfidv.transform(docs).toarray()
vocab = tfidv.get_feature_names()

In [ ]:
vocab

['동물원에서', '바나나를', '봤어', '오늘', '원숭이에게', '원숭이와', '줬어', '코끼리를']

In [ ]:
tfidv.transform(docs).toarray

<bound method _cs_matrix.toarray of <2x8 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>>

In [ ]:
import pandas as pd
df = pd.DataFrame(tfidv.transform(docs).toarray(), columns = vocab)
df

동물원에서      바나나를        봤어  ...      원숭이와        줬어      코끼리를
0  0.335176  0.000000  0.471078  ...  0.471078  0.000000  0.471078
1  0.278943  0.784088  0.000000  ...  0.000000  0.392044  0.000000

[2 rows x 8 columns]

#### 6) Gensim을 활용한 TF-IDF 생성

In [ ]:
import gensim
from gensim import corpora
from gensim.models import TfidfModel

docs = ['오늘 동물원에서 원숭이와 코끼리를 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

doc_ls = [doc.split() for doc in docs]
id2word = corpora.Dictionary(doc_ls)
TDM = [id2word.doc2bow(doc) for doc in doc_ls]
model = TfidfModel(TDM)
tfidf = model[TDM]
tfidf[0]

[(1, 0.5), (2, 0.5), (3, 0.5), (4, 0.5)]

In [ ]:
import pandas as pd
from gensim.matutils import sparse2full

vocab = [id2word[i] for i in id2word.keys()]
TDM_matrix = [sparse2full(doc,len(vocab)).tolist() for doc in tfidf]
pd.DataFrame(TDM_matrix, columns = vocab)

동물원에서   봤어   오늘  원숭이와  코끼리를      바나나를     원숭이에게        줬어
0    0.0  0.5  0.5   0.5   0.5  0.000000  0.000000  0.000000
1    0.0  0.0  0.0   0.0   0.0  0.816497  0.408248  0.408248

In [ ]:
tfidf[1]

[(5, 0.8164965809277261), (6, 0.4082482904638631), (7, 0.4082482904638631)]